### ISSUE TITLE
Run the script

### ISSUE THREAD

**Issue by michielbdejong** [ambanum/TOSBack-CGUs-bridge#2]
I ran it for an hour and got these:
- [snapshots](https://github.com/TosbackCgusBridge-Bot/CGUs-snapshots/commits/import-1599831040)
- [versions](https://github.com/TosbackCgusBridge-Bot/CGUs-versions/commits/import-1599831040)
- no rules were committed (I'm not sure why, must be a bug in the script)

I realized that I couldn't leave it running without leaving my laptop in the office tonight, so I stopped the run and started a new one in a `tmux` session.

**Comment by Ndpnt** [comment]
I looked at the generated versions and it sounds good, great job! :+1:

**Comment by michielbdejong** [comment]
OK, I'll do some sanity checks on the results and then see if I can produce my final PRs for all repos.

**Comment by michielbdejong** [comment]
Fixed quite a few more issues from https://github.com/ambanum/TOSBack-CGUs-bridge/issues?q=is%3Aissue
Running again now, will check the result tomorrow.

**Comment by michielbdejong** [comment]
latest script output (running since Thursday evening):
```sh
crawl_reviewed/youtube.com/Terms of Service.txt Youtube Terms of Service done
Saved ../CGUs/services/Zoosk.json
crawl_reviewed/zoosk.com/Privacy Policy.txt Zoosk Privacy Policy done
crawl_reviewed/zoosk.com/Privacy Policy.txt no file text at tosback2-commit 400f1a367ecadd990bfa11f69be88d0b0717387d
crawl_reviewed/zoosk.com/Privacy Policy.txt no file text at tosback2-commit c15efb8816f611059e56f535f22830c2ede74fe3
crawl_reviewed/zoosk.com/Privacy Policy.txt no file text at tosback2-commit e2d28f9ccf1120d6adff42562a07e0f5d51452eb
crawl_reviewed/zoosk.com/Privacy Policy.txt no file text at tosback2-commit 70f958142f8d337699431cd2502fd6fdf0f1bfb7

**Comment by michielbdejong** [comment]
Output is still the same, and has been since `Oct 18 23:34` (it's now `Oct 19 14:17`).

It apparently hasn't finished its [first git push](https://github.com/ambanum/TOSBack-CGUs-bridge/blob/master/run.sh#L34) yet (branch name is `import-1602787094`).

So looks like the tosback-import.js script is not exiting, maybe it's still waiting for something which is not going to happen anymore... But from the logs it looks like it finished all the services and documents. So tomorrow morning I might just stop the script and resume it from that line.

**Comment by michielbdejong** [comment]
Done:
* https://github.com/TosbackCgusBridge-Bot/CGUs/tree/import-1602787094
* https://github.com/TosbackCgusBridge-Bot/CGUs-snapshots/tree/import-1602787094
* https://github.com/TosbackCgusBridge-Bot/CGUs-snapshots/tree/rebased-1602787094
* https://github.com/TosbackCgusBridge-Bot/CGUs-versions/tree/import-1602787094
* https://github.com/TosbackCgusBridge-Bot/CGUs-versions/tree/rebased-1602787094

CC @Ndpnt

**Comment by Ndpnt** [comment]
We will merge https://github.com/ambanum/CGUs/pull/184 soon.
Before merging, we will invest half a day checking and correcting the services so that services names and IDs fully respect our standard  😃

Thanks @michielbdejong for your work!

**Comment by michielbdejong** [comment]
Great! As I said, let me know if you want me to do a re-run of anything.

I'm working on some other stuff this week, but will soon start up ToS;DR's instance of the same code, and then next year you can still expect the occasional PR from me whenever we update one of the service descriptions on our instance through our community of volunteers on edit.tosdr.org, and when that affects services which you also crawl.

Thanks so much again, for making this awesome collaboration happen!!
